# Generated by Django 6.0.6 on 2026-08-11 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('platform', models.CharField(max_length=100, verbose_name='Площадка')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вознаграждение')),
                ('max_completions', models.PositiveIntegerField(default=1, verbose_name='Максимум выполнений')),
                ('completions', models.PositiveIntegerField(default=0, verbose_name='Выполнено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('taken', 'Взято'), ('submitted', 'Отправлено'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='taken', max_length=20)),
                ('review_url', models.URLField(blank=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='bot.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='bot.telegramuser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'task'), name='unique_user_task')],
            },
        ),
    ]
